<a href="https://colab.research.google.com/github/linaoh02/2025-/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("HElLo World")

#integer
x=3
print("정수: %01d, %02d, %03d, %04d %05d" %(x,x,x,x,x,))

#float
x= 256.123
print ("실수: %.0f, %.1f, %.2f" %(x,x,x))

#string
x= "Hello, World"
print ("문자열: [%s]" %x)

HElLo World
정수: 3, 03, 003, 0003 00003
실수: 256, 256.1, 256.12
문자열: [Hello, World]


In [ ]:
contents = ["Regresion", "Classification", "SYM", "Clustering", "Dimension reduction", "NN", "CNN", "AE", "GAN", "RNN"]

for con in contents:
  if con in ["Regresion", "Classification", "SYM", "Clustering", "Dimension reduction"]:
    print("%s는 기계학습 내용입니다" %con)

  elif con in ["CNN"]:
    print("%s은 convolutional neural network입니다" %con)

  else:
    print("%s은 심층학습 학습 내용입니다" %con)

Regresion는 기계학습 내용입니다
Classification는 기계학습 내용입니다
SYM는 기계학습 내용입니다
Clustering는 기계학습 내용입니다
Dimension reduction는 기계학습 내용입니다
NN은 심층학습 학습 내용입니다
CNN은 convolutional neural network입니다
AE은 심층학습 학습 내용입니다
GAN은 심층학습 학습 내용입니다
RNN은 심층학습 학습 내용입니다


In [ ]:
for (i, con) in enumerate(contents):
  print ("[%d/%d]: %s" %(i, len(contents), con))

[0/10]: Regresion
[1/10]: Classification
[2/10]: SYM
[3/10]: Clustering
[4/10]: Dimension reduction
[5/10]: NN
[6/10]: CNN
[7/10]: AE
[8/10]: GAN
[9/10]: RNN


In [ ]:
def sum (a,b):
  return a+b
x =10.0
y=20.0
print ("%.1f + %.1f = %.1f" %(x, y, sum(x,y)))

10.0 + 20.0 = 30.0


In [ ]:
a = []
b =[1,2,3]
c=["Hello", ",", "world"]
d =[1,2,3,"x","y","z"]
x =[]

print(x)

x.append('a')
print (x)

x.append(123)
print(x)

x.append(["a","b"])
print (x)

[]
['a']
['a', 123]
['a', 123, ['a', 'b']]


In [ ]:
dic = dict()
dic["name"] ="Heekyung"
dic["town"] ="Gwangju"
dic["job"] ="Student"
print (dic)

{'name': 'Heekyung', 'town': 'Gwangju', 'job': 'Student'}


In [ ]:
class  Student:
  #생성자
  def __init__(self, name):
    self.name = name

  #메써드
  def study(self, hard = False) :
    if hard:
      print ("%s 학생은 열심히 공부합니다" %self.name)
    else:
      print ("%s 학생은 공부합니다" %self.name)

s = Student("Heekyung")
s.study()
s.study(hard = True)

Heekyung 학생은 공부합니다
Heekyung 학생은 열심히 공부합니다


2. **벡터, 행렬 연산, 그래프 그리기**

In [ ]:
import numpy as np

In [ ]:
def print_val(x) :
  print ("Type: ", type(x))
  print ("Shape: ", x.shape)
  print ("값:\n", x)
  print (" ")

In [ ]:
x = np.array([1,2,3]) #넘 파일에 어레이로
print_val(x)

x[0] = 5
print_val(x) #시험에서 빈칸 뚫어서 쓰게하기 = np.array([1,2,3]) #넘 파일에 어레이로

x[0] = 5
print_val(x) #시험에서 빈칸 뚫어서 쓰게하기

Type:  <class 'numpy.ndarray'>
Shape:  (3,)
값:
 [1 2 3]
 
Type:  <class 'numpy.ndarray'>
Shape:  (3,)
값:
 [5 2 3]
 
Type:  <class 'numpy.ndarray'>
Shape:  (3,)
값:
 [5 2 3]
 


In [ ]:
y = np.array([[1,2,3],[4,5,6]])
print_val(y)

a = np.ones((3,2)) #보통 셰입을 나타낼때 (3행 2열)(행: 가로줄 열:세로줄)
print_val(a)

a = np.zeros((2,2))
print_val(a)

a = np.eye(3,3) #아이니까...eye.....
print_val(a)


Type:  <class 'numpy.ndarray'>
Shape:  (2, 3)
값:
 [[1 2 3]
 [4 5 6]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (3, 2)
값:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[0. 0.]
 [0. 0.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)
값:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


In [ ]:
a = np.random.random((4,4)) #4,4짜리 행렬에 랜덤한 값이 들어감
print_val(a)

a = np.random.randn(4,4) #rand'n'<- normal(가우시안) distribution / 0에 가까운 값들이 나올 확률이 높음
print_val(a)

Type:  <class 'numpy.ndarray'>
Shape:  (4, 4)
값:
 [[0.00939672 0.17885305 0.17520611 0.7031902 ]
 [0.43030646 0.01006911 0.8468001  0.55584652]
 [0.96951046 0.19680139 0.87777674 0.96342034]
 [0.20697843 0.32084201 0.23101173 0.60199964]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (4, 4)
값:
 [[-0.51595865 -0.59921803  0.09446849  1.85793683]
 [ 2.50494872  1.2803698   0.50048706  1.18412596]
 [-0.14074215 -0.97237778 -0.74342353 -0.29251928]
 [-0.01792092  0.88504378 -1.15052528  1.08949633]]
 


In [ ]:
n = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print_val(a)

Type:  <class 'numpy.ndarray'>
Shape:  (4, 4)
값:
 [[-0.51595865 -0.59921803  0.09446849  1.85793683]
 [ 2.50494872  1.2803698   0.50048706  1.18412596]
 [-0.14074215 -0.97237778 -0.74342353 -0.29251928]
 [-0.01792092  0.88504378 -1.15052528  1.08949633]]
 


In [ ]:
b = a[:2, 1:3] #행0~1, 열 1~2
print_val(b)

row1 = a[1, :] #1번째 행
print_val(row1)

Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[-0.59921803  0.09446849]
 [ 1.2803698   0.50048706]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (4,)
값:
 [2.50494872 1.2803698  0.50048706 1.18412596]
 


In [ ]:
m1 = np.array([[1,2], [3,4]], dtype = np.float64)
m2 = np.array([[5,6], [7,8]], dtype = np.float64)

#elementwise 원소별로 sum더하라
print_val(m1+m2)
print_val(np.add(m1, m2))

Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[ 6.  8.]
 [10. 12.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[ 6.  8.]
 [10. 12.]]
 


In [ ]:
#elementwise difference
print_val (m1-m2)
print_val(np.subtract(m1,m2))

#elementwise product
print_val(m1*m2)
print_val(np.multiply(m1,m2))

Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[-4. -4.]
 [-4. -4.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[-4. -4.]
 [-4. -4.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[ 5. 12.]
 [21. 32.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[ 5. 12.]
 [21. 32.]]
 


In [ ]:
#elementwise division
print_val(m1/m2)
print_val(np.divide(m1,m2))

#elementwise square root
print_val(np.sqrt(m1)) #sqrt = 스퀘어 루트

Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[1.         1.41421356]
 [1.73205081 2.        ]]
 


In [ ]:
m1 = np.array([[1,2],[3,4]]) #(2,2)
m2 = np.array([[5,6],[7,8]]) #(2,2)

v1 = np.array([9,10]) #(2,)
v2 = np.array([11,12]) #(2,)

print_val(m1)
print_val(m2)
print_val(v1)
print_val(v2)

Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[1 2]
 [3 4]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[5 6]
 [7 8]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2,)
값:
 [ 9 10]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2,)
값:
 [11 12]
 


벡터-벡터 연산

In [ ]:
print_val(v1.dot(v2)) #dot이란 dot product의 줄임말
print_val(np.dot(v1,v2))

Type:  <class 'numpy.int64'>
Shape:  ()
값:
 219
 
Type:  <class 'numpy.int64'>
Shape:  ()
값:
 219
 


벡터-행렬 연산

In [ ]:
print_val(m1.dot(m1)) #(2,2) * (2,1) -> (2,1)

print_val(np.dot(m1,v2))
# m1 = (1  2)  v1 = ( 9)   m1*v1= (9+20 = 29) = (29)
#      (3  4)       (10)          (27+40 = 67)  (67)

Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[ 7 10]
 [15 22]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2,)
값:
 [35 81]
 


In [ ]:
#전치 행렬
print_val(m1)
print_val(m1.T)

Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[1 2]
 [3 4]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
값:
 [[1 3]
 [2 4]]
 


In [ ]:
print_val(np.sum(m1)) #행렬의 모든 원소의 합
print_val(np.sum(m1, axis=0)) #shape[0](행)을 압축시키자
print_val(np.sum(m1, axis=1)) #shape[1](열)을 압축시키자

Type:  <class 'numpy.int64'>
Shape:  ()
값:
 10
 
Type:  <class 'numpy.ndarray'>
Shape:  (2,)
값:
 [4 6]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2,)
값:
 [3 7]
 


In [ ]:
m1 = np.array([[1,2,3],[4,5,6]])
print(m1)
print (m1.shape)

print (np.sum(m1))
print (np.sum(m1, axis=0))
print (np.sum(m1, axis=1))

[[1 2 3]
 [4 5 6]]
(2, 3)
21
[5 7 9]
[ 6 15]


In [ ]:
import numpy as np
m1 =  np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
m2 = np.zeros_like(m1)
print_val(m1)
print_val(m2)

Type:  <class 'numpy.ndarray'>
Shape:  (4, 3)
값:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (4, 3)
값:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
 
